
#ifndef _MEASUREMENT_H
#define _MEASUREMENT_H

#ifdef SOS_IDLE_MEASURE
#define SOS_MEASUREMENT_IDLE_START() PORTC &= ~_BV(1)
#define SOS_MEASUREMENT_IDLE_END() PORTC |= _BV(1)
#else
#define SOS_MEASUREMENT_IDLE_START()
#define SOS_MEASUREMENT_IDLE_END()
#endif

#ifdef SOS_MEASURE_DEQUEUE_OVERHEAD
#define SOS_MEASUREMENT_DEQUEUE_START() PORTC |= _BV(1)
#define SOS_MEASUREMENT_DEQUEUE_END() PORTC &= ~_BV(1)
#else
#define SOS_MEASUREMENT_DEQUEUE_START() 
#define SOS_MEASUREMENT_DEQUEUE_END() 
#endif

#ifdef SOS_MEASURE_MALLOC
#define SOS_MEASUREMENT_MALLOC_START() PORTC |= _BV(1)
#define SOS_MEASUREMENT_MALLOC_END() PORTC &= ~_BV(1)
#else
#define SOS_MEASUREMENT_MALLOC_START() 
#define SOS_MEASUREMENT_MALLOC_END() 
#endif

#endif /* #ifndef _MEASUREMENT_H */
