# PROJ is the file name of your module.
PROJ = temp_sensor
SB = tmote
ROOTDIR = ../../../..
INCDIR += -I$(ROOTDIR)/modules/sensordrivers/tmote/include
INCDIR += -I$(ROOTDIR)/drivers/adc/include

include $(ROOTDIR)/modules/Makerules

