PROJ = adc_app
ROOTDIR = ../../../..

SRCS += adc.c adc_sampler.c

INCDIR += -I$(ROOTDIR)/drivers

include $(ROOTDIR)/config/Makerules

vpath adc.c $(ROOTDIR)/drivers/adc/msp430/
vpath adc_sampler.c .
