#-*-Makefile-*-

##########
# PROJECT SETUP
##########
PROJ = elftomini
SRCS += $(PROJ).c elfhelper.c minielflib.c minielfendian.c dispmelf.c sock_utils.c qsort.c
OBJS += $(SRCS:.c=.o)
ROOTDIR = ../../../..

include ../Makerules

