
#ifndef _MEASUREMENT_H
#define _MEASUREMENT_H

#define SOS_MEASUREMENT_IDLE_START()
#define SOS_MEASUREMENT_IDLE_END()

#define SOS_MEASUREMENT_DEQUEUE_START() 
#define SOS_MEASUREMENT_DEQUEUE_END() 

#define SOS_MEASUREMENT_MALLOC_START() 
#define SOS_MEASUREMENT_MALLOC_END() 

#endif /* #ifndef _MEASUREMENT_H */
