# PROJ is the file name of your module.
PROJ = test_sensor
SB = tmote_impact
ROOTDIR = ../../../../../..
INCDIR += -I$(ROOTDIR)/modules/sensordrivers/tmote/sky/adxl321

include $(ROOTDIR)/modules/Makerules

