/**
 * \file adcm1700Const.c
 * \brief ADCM Driver Constants
 * \author Ram Kumar {ram@ee.ucla.edu}
 */

#include <sos_inttypes.h>
#include <sos_types.h>
#include <adcm1700Const.h>


struct register_s register_param_list[] = {
  //  id,                  block,        offset,   length    
  {ADCM_REG_ID, 0x00, 0x00, TWO_BYTE_REGISTER},
  {ADCM_REG_CONTROL, 0x00, 0x02, TWO_BYTE_REGISTER},
  {ADCM_REG_STATUS, 0x00, 0x04, TWO_BYTE_REGISTER},
  {ADCM_REG_SIZE, 0x00, 0x08, TWO_BYTE_REGISTER},
  {ADCM_REG_SENSOR_WID_V, 0x00, 0x18, TWO_BYTE_REGISTER},
  {ADCM_REG_SENSOR_HGT_V, 0x00, 0x1A, TWO_BYTE_REGISTER},
  {ADCM_REG_OUTPUT_WID_V, 0x00, 0x1C, TWO_BYTE_REGISTER},
  {ADCM_REG_OUTPUT_HGT_V, 0x00, 0x1E, TWO_BYTE_REGISTER},
  {ADCM_REG_SENSOR_WID_S, 0x00, 0x20, TWO_BYTE_REGISTER},
  {ADCM_REG_SENSOR_HGT_S, 0x00, 0x22, TWO_BYTE_REGISTER},
  {ADCM_REG_OUTPUT_WID_S, 0x00, 0x24, TWO_BYTE_REGISTER},
  {ADCM_REG_OUTPUT_HGT_S, 0x00, 0x26, TWO_BYTE_REGISTER},
  {ADCM_REG_OUTPUT_FORMAT, 0x00, 0x0A, TWO_BYTE_REGISTER},
  {ADCM_REG_OUTPUT_CTRL_V, 0x02, 0x10, TWO_BYTE_REGISTER},
  {ADCM_REG_PROC_CTRL_V, 0x02, 0x12, TWO_BYTE_REGISTER},
  {ADCM_REG_SZR_IN_WID_V, 0x02, 0x00, TWO_BYTE_REGISTER},
  {ADCM_REG_SZR_IN_HGT_V, 0x02, 0x02, TWO_BYTE_REGISTER},
  {ADCM_REG_SZR_OUT_WID_V, 0x02, 0x04, TWO_BYTE_REGISTER},
  {ADCM_REG_SZR_OUT_HGT_V, 0x02, 0x06, TWO_BYTE_REGISTER},
  {ADCM_REG_SZR_IN_WID_S, 0x02, 0x20, TWO_BYTE_REGISTER},
  {ADCM_REG_SZR_IN_HGT_S, 0x02, 0x22, TWO_BYTE_REGISTER},
  {ADCM_REG_SZR_OUT_WID_S, 0x02, 0x24, TWO_BYTE_REGISTER},
  {ADCM_REG_SZR_OUT_HGT_S, 0x02, 0x26, TWO_BYTE_REGISTER},
  {ADCM_REG_OUTPUT_CTRL_S, 0x02, 0x30, TWO_BYTE_REGISTER},
  {ADCM_REG_PROC_CTRL_S, 0x02, 0x32, TWO_BYTE_REGISTER},
  {ADCM_REG_PADR1, 0x03, 0x06, TWO_BYTE_REGISTER},
  {ADCM_REG_PADR2, 0x90, 0x08, TWO_BYTE_REGISTER},
  {ADCM_REG_PADR3, 0x90, 0x20, TWO_BYTE_REGISTER},
  {ADCM_REG_PADR4, 0x90, 0x60, TWO_BYTE_REGISTER},
  {ADCM_REG_PADR5, 0x90, 0x6C, TWO_BYTE_REGISTER},
  {ADCM_REG_PADR6, 0x90, 0x80, TWO_BYTE_REGISTER},
  {ADCM_REG_FWROW, 0x10, 0x0A, ONE_BYTE_REGISTER},
  {ADCM_REG_FWCOL, 0x10, 0x0B, ONE_BYTE_REGISTER},
  {ADCM_REG_LWROW, 0x10, 0x0C, ONE_BYTE_REGISTER},
  {ADCM_REG_LWCOL, 0x10, 0x0D, ONE_BYTE_REGISTER},
  {ADCM_REG_SENSOR_CTRL, 0x10, 0x1C, ONE_BYTE_REGISTER},
  {ADCM_REG_DATA_GEN, 0x20, 0x5E, TWO_BYTE_REGISTER},
  {ADCM_REG_AF_CTRL1, 0x02, 0x40, TWO_BYTE_REGISTER},
  {ADCM_REG_AF_CTRL2, 0x02, 0x42, TWO_BYTE_REGISTER},
  {ADCM_REG_AE_TARGET, 0x02, 0x5E, TWO_BYTE_REGISTER},
  {ADCM_REG_EREC_PGA, 0x10, 0x0F, ONE_BYTE_REGISTER},
  {ADCM_REG_EROC_PGA, 0x10, 0x10, ONE_BYTE_REGISTER},
  {ADCM_REG_OREC_PGA, 0x10, 0x11, ONE_BYTE_REGISTER},
  {ADCM_REG_OROC_PGA, 0x10, 0x12, ONE_BYTE_REGISTER},
  {ADCM_REG_APS_COEF_GRN1, 0x20, 0x62, TWO_BYTE_REGISTER},
  {ADCM_REG_APS_COEF_RED, 0x20, 0x64, TWO_BYTE_REGISTER},
  {ADCM_REG_APS_COEF_BLUE, 0x20, 0x66, TWO_BYTE_REGISTER},
  {ADCM_REG_APS_COEF_GRN2, 0x20, 0x68, TWO_BYTE_REGISTER},
  {ADCM_REG_RPT_V, 0x02, 0x14, TWO_BYTE_REGISTER},
  {ADCM_REG_ROWEXP_L, 0x10, 0x13, ONE_BYTE_REGISTER},
  {ADCM_REG_ROWEXP_H, 0x10, 0x14, ONE_BYTE_REGISTER},
  {ADCM_REG_SROWEXP, 0x10, 0x15, ONE_BYTE_REGISTER},
  {ADCM_REG_STATUS_FLAGS, 0x21, 0x02, TWO_BYTE_REGISTER},
  {ADCM_REG_SUM_GRN1, 0x05, 0x18, TWO_BYTE_REGISTER},
  {ADCM_REG_SUM_RED, 0x05, 0x1A, TWO_BYTE_REGISTER},
  {ADCM_REG_SUM_BLUE, 0x05, 0x1C, TWO_BYTE_REGISTER},
  {ADCM_REG_SUM_GRN2, 0x05, 0x1E, TWO_BYTE_REGISTER},
  {ADCM_REG_CPP_V, 0x02, 0x08, TWO_BYTE_REGISTER},
  {ADCM_REG_HBLANK_V, 0x02, 0x0A, TWO_BYTE_REGISTER},
  {ADCM_REG_VBLANK_V, 0x02, 0x0C, TWO_BYTE_REGISTER},
  {ADCM_REG_CLK_PER, 0x00, 0x06, TWO_BYTE_REGISTER},
  {ADCM_REG_AE2_ETIME_MIN, 0x02, 0x58, TWO_BYTE_REGISTER},
  {ADCM_REG_AE2_ETIME_MAX, 0x02, 0x5A, TWO_BYTE_REGISTER},
  {ADCM_REG_AE_GAIN_MAX, 0x02, 0x54, TWO_BYTE_REGISTER},
  // this must always go last
  {IMAGER_NUMBER_OF_REGISTERS, 1, 1, 1},
};

struct register_s * lookup_register (uint16_t registerName)
{
  int i;
  for (i = 0;
       register_param_list[i].registerName != IMAGER_NUMBER_OF_REGISTERS; i++)
    if (register_param_list[i].registerName == registerName)
      return &(register_param_list[i]);
  // not found!! 
  return NULL;
}
