# change the project name to reflect what you have named your test
PROJ = accel_test
ROOTDIR = $(SOSROOT)
# change these two lines to reflect the driver board you are testing
INCDIR += -I$(ROOTDIR)/modules/sensordrivers/h34c/include/
SB = h34c

include $(ROOTDIR)/modules/Makerules

