
# PROJ is the file name of your module.
#PROJ = tpsn_app
PROJ = test_tpsn
ROOTDIR = ../../../..
#SRCS += tpsn.c test_tpsn.c

#include $(ROOTDIR)/config/Makerules
include $(ROOTDIR)/modules/Makerules

vpath tpsn.c $(ROOTDIR)/modules/tpsn/
vpath test_tpsn.c .
