# change the project name to reflect what you have named your test
PROJ = photo_temp_test
ROOTDIR = $(SOSROOT)
# change these two lines to reflect the driver board you are testing
INCDIR += -I$(ROOTDIR)/modules/sensordrivers/mts310/include/
SB = mts310 

include $(ROOTDIR)/modules/Makerules

