
# PROJ is the file name of your module.
PROJ = tpsn_app
ROOTDIR = ../../..
SRCS += tpsn.c test_tpsn.c

include $(ROOTDIR)/config/Makerules

vpath tpsn.c $(ROOTDIR)/extensions/tpsn/
vpath test_tpsn.c .
