#change the project name to reflect the test you have created
PROJ = battery_test
ROOTDIR = $(SOSROOT)
INCDIR += -I$(ROOTDIR)/modules/sensordrivers/mts310/include/
SB = mts310
include $(ROOTDIR)/modules/Makerules
