#-*-Makefile-*-

##########
# PROJECT SETUP
##########
PROJ = melfread
SRCS += $(PROJ).c minielflib.c minielfendian.c dispmelf.c elfhelper.c sock_utils.c qsort.c
OBJS += $(SRCS:.c=.o)
ROOTDIR = ../../../..

include ../Makerules