
# PROJ is the file name of your module.
# TODO: modify to the file name of this module without '.c'
PROJ = script_loader

# TODO: modify ROOTDIR to point to sos-1.x.  
ROOTDIR = ../../..

# TODO: modify to specify the platform this module supports
SUPPORTLIST = cyclops mica2 micaz xyz avrora cricket tmote

include $(ROOTDIR)/modules/Makerules


